### ISSUE TITLE
How does mask_to_tcl work?

### ISSUE THREAD

**Issue by techkang** [princewang1994/TextSnake.pytorch#22]
I have two questions about function mask_to_tcl in util/detection.py.
1. Why not change` result.append(np.array([x_shift, y_shift, radii]))` to ` result.append(np.array([x_c, y_c, radii]))`? I tried and F score raised from 0.657 to 0.663, and it makes more sense.
2. What are `x_shift_pos` and `x_shift_neg`'s purpose?

**Comment by princevandev** [comment]
thank you for pointing out the result appending error, I'll try it in time. 
For the second question, you can image that the $\theta$ in paper is a direction-insensitive parameter due to bottom finding method is text direction irrelevant, that is, in the $\theta$'s prediction, $\theta$ or $\theta + \pi$ can appear in the same text instance, which causes the "tuning back" of tcl in the inference phase. My solution: every time I chose a further point in striding with $\theta$ and $\theta + \pi$(+/-, namely `x_shift_pos` and `x_shift_neg`). In this way, it guarantees that tcl finding can keep in one direction.
